author:
    email: hi@guhub.cn
    name: Eltrac
    avatar: https://image.guhub.cn/uPic/2025/12/once-drowned-koala-king.jpg
email: hi@guhub.cn
logo: "https://image.guhub.cn/uPic/2025/05/header.png!w160"
mainSections:
  - essays
  - posts
  - fictions
  - library
favicon: /favicon.png
footerExternalLinks:
  - name: GitHub
    link: https://github.com/BigCoke233/geek-death-project
    icon: https://image.guhub.cn/uPic/2025/01/NqL5b5.png
  - name: Mastodon
    link: https://c7.io/@eltrac
    icon: /img/mastodon.svg
  - name: Telegram Channel
    link: https://t.me/geedeapro
    icon: /img/telegram.svg
  - name: RSS Feed
    link: /index.xml
    icon: /icons/rss.svg
giscus:
  repo: BigCoke233/geek-death-project
  repoId: R_kgDONPoyVw
  category: General
  categoryId: DIC_kwDONPoyV84Clumc
  mapping: og:title
  strict: 1
  reactionsEnabled: 0
  emitMetadata: 0
  inputPosition: top
  theme: preferred_color_scheme
